### ISSUE TITLE
Problem in executing using GUIX studio 6.1.0.0 in windows OS

### ISSUE THREAD

**Issue by armembedded** [azure-rtos/guix#12] opened 2020-12-20 11:40 UTC
I installed GUIX studio 6.1.0.0 in the windows operating system but the program does not start and display an error. 

how to resolve these issues?

error message title: 
The procedure entry point UiaDisconnectProvider could not be located in the dynamic link library UIAutomationCore.DLL

**Comment by jdeere5220** [comment] 2020-12-23 16:41
Can you provide your complete Windows version information please? Thank you!

**Comment by jdeere5220** [comment] 2020-12-24 19:49
I believe this error is caused by running an old version of Windows. You need to run minimum Windows 8, and starting next year Windows 10.

**Comment by armembedded** [comment] 2020-12-26 08:41
> Can you provide your complete Windows version information please? Thank you!

Windows 7 ultimate

**Comment by jdeere5220** [comment] 2021-01-04 17:03
Yes, you will need to update to Windows 10 to run GUIX Studio and TraceX applications.

**Comment by yuxin-azrtos** [comment] 2021-01-28 22:27
Looks like this issue is resolved.  Close it.  Feel free to reopen it if you have additional comments or feedback. Thanks!

**Closed by yuxin-azrtos** 2021-01-28 22:27 UTC
