### ISSUE TITLE
In rare cases, the sprite does not stop updating.

### ISSUE THREAD

**Issue by yam-mas** [azure-rtos/guix#32] opened 2021-12-17 02:10 UTC
Hello.
I use gx_sprite_start() to start updating sprites, and then call gx_sprite_stop() to stop the sprite updating, but in rare cases the sprite updating does not stop.
In this case, I found out that _gx_system_timer_stop(), which is called in gx_sprite_stop(), is causing an error.

In the normal flow
gx_sprite_start()
=>
gx_system_timer_update()
=>
At timer expiration
_gx_system_timer_stop()
=>
GX_EVENT_TIMER event issued
=>
gx_sprite_update() in response to GX_EVENT_TIMER event
=>
_gx_system_timer_start() re-set timer
=>
gx_sprite_stop() at this timing
=>
Stop updating

But if
In case of an error
gx_sprite_start()
=>
gx_system_timer_update()
=>
In case of timer expiration
_gx_system_timer_stop()
=>
GX_EVENT_TIMER event issued
=>
gx_sprite_stop() at this timing
　Error because stop() has already been done
=>
gx_sprite_update() in response to GX_EVENT_TIMER event
=>
_gx_system_timer_start()Reset timer
=>
After that, update() will keep running.

and between the stop() by update() and the start() by GX_EVENT_TIMER
I think this happens when gx_sprite_stop() is called.
This is due to the fact that gx_sprite_stop() has a call-prohibited section, but please let me know how to solve this problem.

**Comment by jdeere5220** [comment] 2021-12-17 15:13
@yam-mas thank you for the report, we will investigate and report back to you.

**Comment by jdeere5220** [comment] 2021-12-17 17:01
@yam-mas I believe we have found and fixed the issue. The fix will be in our next patch release (January I believe), but if you need the fix right away please provide your email address and I will send you the modified file directly.

**Comment by yam-mas** [comment] 2021-12-19 23:52
@jdeere5220, thanks for the quick response.
If it will be included in the next patch release, you don't have to send it to me via email.
Thank you!

**Comment by jdeere5220** [comment] 2021-12-20 16:58
@yam-mas Actually since you are able to reproduce the problem I would prefer to get the change to you prior to our next release and confirm we have the issue fixed. Either way is fine.

**Comment by yam-mas** [comment] 2021-12-22 00:06
@jdeere5220, thanks for the reply.
I can check the effect of the fix, but I was concerned about putting my email address here.
Is it possible to attach a file to this web form?

**Comment by TiejunMS** [comment] 2021-12-22 00:27
@yam-mas , one possible solution to avoid public your email is to send an email to azure-rtos-support@microsoft.com. We can reply you directly.

**Comment by yam-mas** [comment] 2021-12-22 00:35
TiejunMS, thanks for the reply.
I've just sent you an email.
Thank you for your time.

**Comment by jdeere5220** [comment] 2021-12-23 19:27
Sent the modified source file.

**Closed by jdeere5220** 2021-12-23 19:27 UTC
